# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hello World
#'
#' simple example of creating two matrices and returning the result of an
#' operation on them
#'
#' @return matrix
rcpparma_hello_world <- function() {
    .Call('container_rcpparma_hello_world', PACKAGE = 'container')
}

#' Outer product
#'
#' another simple example: outer product of a vector,
#' returning a matrix
#'
#' @param x column vector
#' @return matrix with the outer product
#'
rcpparma_outerproduct <- function(x) {
    .Call('container_rcpparma_outerproduct', PACKAGE = 'container', x)
}

#' Inner product
#'
#' another simple example: inner product of a vector,
#' returning a scalar
#'
#' @param x column vector
#' @return scalar with the inner product
#'
rcpparma_innerproduct <- function(x) {
    .Call('container_rcpparma_innerproduct', PACKAGE = 'container', x)
}

#' Return both the inner and outer product
#'
#' Return a list with both the inner and outer product
#'
#' @param x column vector
#' @return list with both the inner and outer product
#'
rcpparma_bothproducts <- function(x) {
    .Call('container_rcpparma_bothproducts', PACKAGE = 'container', x)
}

